alter table cmdb_instance add column mainten_factory varchar(40) null comment '维保厂家';
update cmdb_instance i, cmdb_instance_antivirussystem m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_antivirussystem drop column mainten_factory;
update cmdb_instance i, cmdb_instance_backup_storage m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_backup_storage drop column mainten_factory;
update cmdb_instance i, cmdb_instance_ddos m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_ddos drop column mainten_factory;
update cmdb_instance i, cmdb_instance_dict_config_his m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_dict_config_his drop column mainten_factory;
update cmdb_instance i, cmdb_instance_diskarray m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_diskarray drop column mainten_factory;
update cmdb_instance i, cmdb_instance_distributed m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_distributed drop column mainten_factory;
update cmdb_instance i, cmdb_instance_firewall m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_firewall drop column mainten_factory;
update cmdb_instance i, cmdb_instance_intrusiondefense m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_intrusiondefense drop column mainten_factory;
update cmdb_instance i, cmdb_instance_intrusiontest m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_intrusiontest drop column mainten_factory;
update cmdb_instance i, cmdb_instance_ip_san m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_ip_san drop column mainten_factory;
update cmdb_instance i, cmdb_instance_leakscan m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_leakscan drop column mainten_factory;
update cmdb_instance i, cmdb_instance_loadbalance m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_loadbalance drop column mainten_factory;
update cmdb_instance i, cmdb_instance_netswitch m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_netswitch drop column mainten_factory;
update cmdb_instance i, cmdb_instance_netvpn m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_netvpn drop column mainten_factory;
update cmdb_instance i, cmdb_instance_network_ips m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_network_ips drop column mainten_factory;
update cmdb_instance i, cmdb_instance_network_manager m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_network_manager drop column mainten_factory;
update cmdb_instance i, cmdb_instance_nosql_storage m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_nosql_storage drop column mainten_factory;
update cmdb_instance i, cmdb_instance_physical_machine m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_physical_machine drop column mainten_factory;
update cmdb_instance i, cmdb_instance_router m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_router drop column mainten_factory;
update cmdb_instance i, cmdb_instance_shunt m set i.mainten_factory = m.mainten_factory where i.id = m.instance_id;
ALTER table cmdb_instance_shunt drop column mainten_factory;