export const columnBase = {
  'deviceSerialNumber': '设备序列号',
  'resourcePool':   '资源池',
  'department1':  '一级部门',
  'department2':'二级部门',
  'systemName': '业务系统',
  'deviceClassify':'设备分类',
  'deviceType': '设备类型',
  'deviceModel': '设备型号',
  'deviceName': '设备名称',
  'ip': 'IP',
  'assetsNumber': '资产编号',
  'projectName': '项目名称',
  'projectNo': '合同编号',
  'contractContact': '合同联系人',
  'contractContactPhone':  '合同联系人电话',
  'contractContactEmail':  '合同联系人邮箱',
  'maintenanceType': '维保类型',
  'deviceArea': '设备区域',
  'maintenanceProjectType':  '维保对象类型',
  'procureType': '采购类型',
  'money': '金额(万)',
  'produceName':  '服务供应商', // 合同供应商
  'produceConcat':  '服务联系人',
  'producePhone':  '服务联系人电话',
  'produceEmail':  '服务联系人邮箱',
  'serviceType': '服务类型',
  'service_start_time': '服务开始时间',
  'warranty_date': '出保时间',// 出保时间就是服务结束时间
  'buyMainten':  '是否购买维保',
  'originBuy':  '是否需原厂维保',
  'originBuyExplain':  '原厂维保购买必要性说明',
  'admin': '维保管理员',
  'preTax': '税前',
  'afterTax': '税后',
  'unitPrice': '单价',
  'totalPrice': '总价',
  'payMethod': '结算方式',
  'discountAmount': '折扣后金额',
  'discountRate': '折扣率'
}


